// Code generated by go generate; DO NOT EDIT.
package resettest

// Reset сбрасывает все поля структуры Test.
func (rs *Test) Reset() {
	if rs == nil {
		return
	}

	rs.A = ""

	rs.B = 0

	rs.C = rs.C[:0]

	clear(rs.D)

	if rs.F != nil {
		if resetter, ok := interface{}(rs.F).(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}

}
